# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded kdata 1.0 [list source [file join $dir kdata.tcl]]
package ifneeded kdata::language::java 1.0 [list source [file join $dir kd_java.tcl]]
package ifneeded kdata::language::python 1.0 [list source [file join $dir kd_python.tcl]]
package ifneeded kdata::language::tcl 1.0 [list source [file join $dir kd_tcl.tcl]]
